version: 2.1

jobs:
  pytest:
    parameters:
      image:
        description: "Docker image to run tests in"
        default: cimg/python:3.8
        type: string
      python_version:
        description: "Python version used to separate cache"
        default: "py38"
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-<< parameters.python_version>>-{{ .Branch }}-{{ checksum "test-requirements.txt" }}
            - deps-<< parameters.python_version>>-{{ .Branch }}-
            - deps-<< parameters.python_version>>-
      - run:
          name: Install test requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r test-requirements.txt .
      - save_cache:
          key: deps-<< parameters.python_version>>-{{ .Branch }}-{{ checksum "test-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Test run
          command: |
            . venv/bin/activate
            mkdir test_results
            mv lightfm _lightfm
            py.test -xv --junitxml=test_results/junit.xml tests
      - store_test_results:
          path: test_results
  lint:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-lint-{{ .Branch }}-{{ checksum "lint-requirements.txt"}}
            - v2-deps-lint-{{ .Branch }}-
            - v2-deps-lint-
      - run:
          name: Install lint requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r lint-requirements.txt
      - save_cache:
          key: v2-deps-lint-{{ .Branch }}-{{ checksum "lint-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            flake8 setup.py lightfm tests
            black --check setup.py lightfm tests

workflows:
  version: 2
  test:
    jobs:
      - lint
      - pytest:
          image: cimg/python:3.10
          python_version: py310
      - pytest:
          image: cimg/python:3.9
          python_version: py39
      - pytest:
          image: cimg/python:3.8
          python_version: py38
      - pytest:
          image: cimg/python:3.7
          python_version: py37
